version: "1"

# Define policies for infrastructure governance
policies:
  - name: enforce-resource-tagging
    type: plan
    body: |
      package spacelift

      # Enhanced tag enforcement for 2025 requirements
      warn[msg] {
        resource := input.terraform.resource_changes[_]
        tags := resource.change.after.tags
        not tags.ManagedBy
        msg := sprintf("Resource %s missing ManagedBy tag", [resource.address])
      }

      deny[msg] {
        resource := input.terraform.resource_changes[_]
        tags := resource.change.after.tags
        not tags.GitOps
        msg := sprintf("Resource %s missing GitOps tag", [resource.address])
      }

# Single stack configuration for unified infrastructure
stacks:
  aws-infrastructure:
    repository: qballscholar/spacelift-gitops-workflow
    branch: main
    project_root: .  # Root directory containing terraform.tf
    autodeploy: false  # Enable CI/CD on push
    labels:
      - key: feature:enable_git_checkout
        value: "true"
    worker_pool: public
    administrative: false  # Disable unless needing special privileges
    description: "Unified AWS Infrastructure (VPC + EKS)"
    before_init:
      - terraform init -reconfigure  # Ensure module initialization
    after_apply:
      - echo "Infrastructure deployed successfully"

# Configure environment variables for all stacks
environment:
  AWS_REGION: us-east-1
  TF_IN_AUTOMATION: "true"

# Configure the worker pool (no changes needed)
worker_pools:
  - name: public
    executor_type: public
